/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;


public class Restaurant extends ReviewInterface {
    private  String name;
    private int stars;
    private String price;

    public Restaurant(String name , int stars , String price){
        super(Review.body , Review.auther , Review.stars);
        this.name = name;
        this.stars = stars;
        this.price = price;
    }

    public String getName() {
        return name;
    }

    public int getStars(){
        return stars;
    }

    public String getPrice(){
        return price;
    }


    public Object addReview(String body , String auther , int stars){
        this.body = body;
        this.auther = auther;
        this.stars = stars ; 
        return null ;
    }


@Override
    public String toString() {
        return "Restaurant name: " + getName() + " with Stars" + getStars() + " and the price is : " + getPrice() ;
    }

public String getAuther() {
    return null;
}

public String getBody() {
    return null;
}

}
    
