/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

import org.junit.jupiter.api.Test;

import static org.junit.Assert.assertTrue;
import static org.junit.jupiter.api.Assertions.*;

public class LibraryTest {
    @Test void someTrue(){
        Library underTestLibrary = new Library();
        assertTrue(underTestLibrary.someTrue() , );
    }

    @Test public void someLibraryMethodReturnsTrue() {
        Object category;
        Restaurant classUnderTest;
        classUnderTest = new Restaurant();

    }
}