/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

import org.junit.Test;

public class RestaurantTest {
    private Object PriceCategory;

    @Test public void someLibraryMethodReturnsTrue() {
        Object category;
        Restaurant classUnderTest;
        classUnderTest = new Restaurant();

    }
}